name: Update AUR package

on:
    workflow_dispatch:
    schedule:
      - cron: "0 */4 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  

      - name: Update PKGBUILD
        id: update
        run: |
          ./update.sh

      - name: Commit changes
        if: ${{ steps.update.outcome == 'success' }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add PKGBUILD
          git commit -m "Update PKGBUILD"
          git push

      - name: Publish AUR package
        if: ${{ steps.update.outcome == 'success' }}
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
            pkgname: ryujinx-ava-bin
            pkgbuild: ./PKGBUILD
            commit_username: ${{ secrets.AUR_USERNAME }}
            commit_email: ${{ secrets.AUR_EMAIL }}
            ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
            commit_message: Update AUR package
            ssh_keyscan_types: rsa,dsa,ecdsa,ed25519