name: Update AUR package

on:
    workflow_dispatch:
    schedule:
      - cron: "0 */4 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  

      - name: Update PKGBUILD
        id: update
        run: |
          ./update.sh

      - name: Get Current Version
        id: get_version
        run: |
          echo "::set-output name=version::$(grep 'pkgver=' PKGBUILD | cut -d'=' -f2)"

      - name: Commit and push changes
        if: ${{ steps.update.outcome == 'success' }}
        uses: EndBug/add-and-commit@v9
        with:
            default_author: github_actions
            message: Update to ${{ steps.get_version.outputs.version }}
            add: PKGBUILD
            push: true

      - name: Get last commit message
        id: last_commit
        run: echo "::set-output name=message::$(git log -1 --pretty=format:%s)"

      - name: Publish AUR package
        if: ${{ steps.update.outcome == 'success' }}
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
            pkgname: ryujinx-ava-bin
            pkgbuild: ./PKGBUILD
            commit_username: ${{ secrets.AUR_USERNAME }}
            commit_email: ${{ secrets.AUR_EMAIL }}
            ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
            commit_message: ${{ steps.last_commit.outputs.message }}
            ssh_keyscan_types: rsa,dsa,ecdsa,ed25519