name: Update AUR package

on:
    workflow_dispatch:
    schedule:
      - cron: "0 */6 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
    #   - name: Install prerequisites
    #     run: |
    #       echo "ParallelDownloads = 10" >> /etc/pacman.conf
    #       echo "\n" && echo "[multilib]" >> /etc/pacman.conf
    #       echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
    #       pacman -Syu base-devel sudo meson python-mako glslang hub --noconfirm
    
      - name: Set up Git
        run: |
          git config --global user.name "honjow"
          git config --global user.email "honjow311@gmail.com"   

      - name: Update PKGBUILD
        id: update
        run: |
          # 获取依赖项目的最新版本号
          ./update.sh

      - name: Commit changes
        if: ${{ steps.update.outcome == 'success' }}
        run: |
          git add PKGBUILD .SRCINFO
          git commit -m "Update PKGBUILD"

      - name: Push changes
        if: ${{ steps.update.outcome == 'success' }}
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}