name: Update AUR package

on:
    workflow_dispatch:
    schedule:
      - cron: "0 */4 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  

      - name: Update PKGBUILD
        id: update
        run: |
          ./update.sh

      - name: Commit and push changes
        if: ${{ steps.update.outcome == 'success' }}
        uses: EndBug/add-and-commit@v9
        with:
            default_author: github_actions
            message: Update PKGBUILD
            add: PKGBUILD
            push: true

      - name: Publish AUR package
        if: ${{ steps.update.outcome == 'success' }}
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
            pkgname: ryujinx-ava-bin
            pkgbuild: ./PKGBUILD
            commit_username: ${{ secrets.AUR_USERNAME }}
            commit_email: ${{ secrets.AUR_EMAIL }}
            ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
            commit_message: Update AUR package
            ssh_keyscan_types: rsa,dsa,ecdsa,ed25519