name: Update AUR package

on:
    workflow_dispatch:
    schedule:
      - cron: "*/5 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    container:
        image: archlinux:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Git
        run: |
          git config --global user.name "honjow"
          git config --global user.email "honjow311@gmail.com"   

      - name: Update PKGBUILD
        run: |
          # 获取依赖项目的最新版本号
          ./update.sh